name: lint
on: push
jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        name: 'setup node'
        with:
          node-version: '16.x'

      - name: Install packages
        run: make install

      - name: Run eslinter
        run: make lint
